### ISSUE TITLE
Incorrect username or password

### ISSUE THREAD

**Issue by Latias94** [Ma63d/leetcode-spider#10]
前两天还能正常用的，现在就  incorrect username or password 了，应该是 LeetCode 反爬虫策略改了。

**Comment by AlbertRui** [comment]
我也遇到了这个问题

**Comment by lezhangisu** [comment]
Same error. 
[lc-spider] ERROR - { AssertionError [ERR_ASSERTION]: incorrect username or password
    at /usr/local/lib/node_modules/leetcode-spider/lib/spider.js:126:12
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/leetcode-spider/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: '!=' }

**Comment by Kiwitwitter** [comment]
Same problem.
期待下次更新。

**Comment by luchenqun** [comment]
期待更新，确实提示密码错了。

**Comment by fakeYanss** [comment]
waiting for update

**Comment by MLuminary** [comment]
期待下次更新，刚开始还以为是和 Github 关联的原因

**Comment by joeyleee** [comment]
我也遇到了相同的问题啊

**Comment by yihan-us** [comment]
Same problem here.

**Comment by Latias94** [comment]
@yihan-us 感谢PR，已解决。

**Comment by Ma63d** [comment]
已合入 @yihan-us 的 RP, 已发布 NPM. 更新至新版本后就可以使用.

**Comment by nch3ng** [comment]
大家這都有解決了嗎？

我還是出現一樣的問題，帳號應該都沒錯 token 也 get 了，但就出現一樣的訊息

[21:58:17] [lc-spider] INFO - token get
[21:58:17] [lc-spider] ERROR - { AssertionError [ERR_ASSERTION]: incorrect username or password
    at /Users/natec/.nvm/versions/node/v9.11.2/lib/node_modules/leetcode-spider/lib/spider.js:126:12
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/natec/.nvm/versions/node/v9.11.2/lib/node_modules/leetcode-spider/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: '!=' }
