### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by ZhaoxiZhang** [Ma63d/leetcode-spider#12]
今天在使用leetcode-spider的时候一直报错，其报错信息如下：
```
[10:21:26] [lc-spider] INFO - token get
[10:21:28] [lc-spider] INFO - login successfully
[10:21:46] [lc-spider] ERROR - { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
[10:21:46] [lc-spider] ERROR - Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ZhaoxiZhang** [comment]
应该是网络问题  我走了一下代理  现在可以了~
