### ISSUE TITLE
spider报错，求解决

### ISSUE THREAD

**Issue by BetterAA** [Ma63d/leetcode-spider#9]
运行lc-spider，报错，信息如下，不太懂这个东西，求大佬解决~
/usr/local/lib/node_modules/leetcode-spider/lib/spider.js:140
    let [, body] = yield request.get('/api/problems/algorithms/')
        ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/leetcode-spider/lib/entry.js:53:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by Ma63d** [comment]
node 版本的问题，你 node 版本多少？麻烦升级至比较高的版本。

**Comment by BetterAA** [comment]
果然是我的node的版本问题，很久没用了，版本不是最近的，谢谢楼主~~
